name: Update GitHub Stats

on:
  schedule:
    - cron: "0 5 * * *"  # Ejecuta todos los días a las 5 UTC
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch GitHub Stats
        run: |
          curl -o github-stats-1.svg "https://github-readme-stats.vercel.app/api?username=${{ github.actor }}&include_all_commits=true&count_private=true&theme=react&show_icons=true&token=${{ secrets.GH_TOKEN }}"
          curl -o github-stats-2.svg "https://github-readme-stats.vercel.app/api?username=${{ github.actor }}&include_all_commits=true&count_private=true&layout=compact&theme=city_lights&token=${{ secrets.GH_TOKEN }}"
          curl -o github-streak.svg "https://github-readme-streak-stats.herokuapp.com/?user=${{ github.actor }}&theme=dark&token=${{ secrets.GH_TOKEN }}"
          curl -o github-trophies.svg "https://github-profile-trophy.vercel.app/?username=${{ github.actor }}&theme=algolia&no-frame=false&no-bg=false&margin-w=4&token=${{ secrets.GH_TOKEN }}"

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add github-stats-1.svg github-stats-2.svg github-streak.svg github-trophies.svg
          git commit -m "Update GitHub stats"
          git push
